"""empty message

Revision ID: 997fc964f055
Revises: a39012500d8d
Create Date: 2023-02-09 15:52:59.232904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997fc964f055'
down_revision = 'a39012500d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
